export interface Preset {
  name: string;
  description: string;
  category: string;
  filters: {
    [key: string]:
      | number
      | boolean
      | Array<{ r: number; g: number; b: number }>;
  };
}

export const presets: Preset[] = [
  // Moody & Dark (15 presets)
  {
    name: "Dark Academia",
    description: "Rich dark tones with vintage scholarly feel",
    category: "Moody & Dark",
    filters: {
      brightness: 95,
      contrast: 120,
      saturation: 85,
      temperature: -8,
      tint: -5,
      highlights: -25,
      shadows: 15,
      noise: 20,
      vignette: 35,
    },
  },
  {
    name: "Gothic Romance",
    description: "Deep shadows with dramatic contrast",
    category: "Moody & Dark",
    filters: {
      brightness: 90,
      contrast: 130,
      saturation: 80,
      temperature: -10,
      highlights: -30,
      shadows: 20,
      vignette: 45,
    },
  },
  {
    name: "Midnight Mystery",
    description: "Deep blues and mysterious shadows",
    category: "Moody & Dark",
    filters: {
      brightness: 92,
      contrast: 115,
      saturation: 90,
      temperature: -12,
      tint: 5,
      highlights: -25,
      shadows: 18,
      vignette: 40,
    },
  },
  {
    name: "Film Noir",
    description: "Classic black and white with dramatic contrast",
    category: "Moody & Dark",
    filters: {
      brightness: 95,
      contrast: 140,
      saturation: 0,
      grayscale: 100,
      highlights: -20,
      shadows: 25,
      vignette: 35,
      noise: 25,
    },
  },
  {
    name: "Dark Fade",
    description: "Subtle dark tones with faded blacks",
    category: "Moody & Dark",
    filters: {
      brightness: 98,
      contrast: 105,
      saturation: 85,
      temperature: -5,
      highlights: -15,
      shadows: 30,
      vignette: 25,
    },
  },
  {
    name: "Moody Blues",
    description: "Cool tones with deep shadows",
    category: "Moody & Dark",
    filters: {
      brightness: 95,
      contrast: 110,
      saturation: 90,
      temperature: -15,
      tint: 5,
      highlights: -20,
      shadows: 15,
    },
  },
  {
    name: "Dark Forest",
    description: "Deep greens and moody shadows",
    category: "Moody & Dark",
    filters: {
      brightness: 93,
      contrast: 120,
      saturation: 95,
      temperature: -8,
      tint: 8,
      highlights: -25,
      shadows: 20,
      vignette: 30,
    },
  },
  {
    name: "Noir Portrait",
    description: "Dramatic black and white portrait style",
    category: "Moody & Dark",
    filters: {
      brightness: 97,
      contrast: 135,
      saturation: 0,
      grayscale: 100,
      highlights: -15,
      shadows: 20,
      vignette: 40,
    },
  },
  {
    name: "Dark Minimal",
    description: "Clean dark tones with subtle contrast",
    category: "Moody & Dark",
    filters: {
      brightness: 95,
      contrast: 108,
      saturation: 90,
      temperature: -5,
      highlights: -10,
      shadows: 15,
      vignette: 20,
    },
  },
  {
    name: "Stormy",
    description: "Dramatic storm-like atmosphere",
    category: "Moody & Dark",
    filters: {
      brightness: 92,
      contrast: 125,
      saturation: 85,
      temperature: -10,
      highlights: -30,
      shadows: 25,
      vignette: 35,
    },
  },
  {
    name: "Dark Rustic",
    description: "Moody vintage with warm undertones",
    category: "Moody & Dark",
    filters: {
      brightness: 94,
      contrast: 115,
      saturation: 85,
      temperature: 5,
      highlights: -20,
      shadows: 20,
      vignette: 30,
      noise: 15,
    },
  },
  {
    name: "Night City",
    description: "Urban nighttime atmosphere",
    category: "Moody & Dark",
    filters: {
      brightness: 95,
      contrast: 120,
      saturation: 95,
      temperature: -12,
      highlights: -25,
      shadows: 15,
      vignette: 35,
    },
  },
  {
    name: "Dark Contrast",
    description: "High contrast dark tones",
    category: "Moody & Dark",
    filters: {
      brightness: 90,
      contrast: 145,
      saturation: 85,
      temperature: -5,
      highlights: -35,
      shadows: 25,
      vignette: 40,
    },
  },
  {
    name: "Moonlight",
    description: "Soft dark tones with blue cast",
    category: "Moody & Dark",
    filters: {
      brightness: 96,
      contrast: 110,
      saturation: 90,
      temperature: -15,
      tint: -5,
      highlights: -15,
      shadows: 20,
      vignette: 25,
    },
  },
  {
    name: "Shadow Play",
    description: "Emphasis on shadow detail",
    category: "Moody & Dark",
    filters: {
      brightness: 93,
      contrast: 125,
      saturation: 88,
      temperature: -8,
      highlights: -20,
      shadows: 30,
      vignette: 35,
    },
  },

  // Vintage & Film (15 presets)
  {
    name: "Kodak Gold",
    description: "Warm vintage film with golden tones",
    category: "Vintage & Film",
    filters: {
      brightness: 105,
      contrast: 110,
      saturation: 115,
      temperature: 15,
      tint: -5,
      highlights: -10,
      shadows: 15,
      noise: 20,
    },
  },
  {
    name: "Classic Chrome",
    description: "Vintage chrome film simulation",
    category: "Vintage & Film",
    filters: {
      brightness: 102,
      contrast: 120,
      saturation: 85,
      temperature: -5,
      highlights: -15,
      shadows: 20,
      noise: 15,
    },
  },
  {
    name: "Vintage Color",
    description: "Classic color film look",
    category: "Vintage & Film",
    filters: {
      brightness: 103,
      contrast: 115,
      saturation: 95,
      temperature: 8,
      highlights: -12,
      shadows: 15,
      noise: 18,
    },
  },
  {
    name: "Faded Film",
    description: "Subtle faded vintage look",
    category: "Vintage & Film",
    filters: {
      brightness: 108,
      contrast: 95,
      saturation: 85,
      temperature: 5,
      highlights: -8,
      shadows: 12,
      noise: 12,
    },
  },
  {
    name: "Retro 400",
    description: "Classic 400 speed film simulation",
    category: "Vintage & Film",
    filters: {
      brightness: 104,
      contrast: 118,
      saturation: 90,
      temperature: 10,
      highlights: -15,
      shadows: 18,
      noise: 25,
    },
  },
  {
    name: "Vintage BW",
    description: "Classic black and white film",
    category: "Vintage & Film",
    filters: {
      brightness: 105,
      contrast: 125,
      saturation: 0,
      grayscale: 100,
      highlights: -10,
      shadows: 15,
      noise: 20,
    },
  },
  {
    name: "Muted Tones",
    description: "Subtle vintage color palette",
    category: "Vintage & Film",
    filters: {
      brightness: 106,
      contrast: 105,
      saturation: 80,
      temperature: 3,
      highlights: -5,
      shadows: 10,
      noise: 15,
    },
  },
  {
    name: "Warm Vintage",
    description: "Warm-toned vintage look",
    category: "Vintage & Film",
    filters: {
      brightness: 105,
      contrast: 112,
      saturation: 95,
      temperature: 12,
      highlights: -12,
      shadows: 15,
      noise: 18,
    },
  },
  {
    name: "Cool Vintage",
    description: "Cool-toned vintage aesthetic",
    category: "Vintage & Film",
    filters: {
      brightness: 104,
      contrast: 110,
      saturation: 90,
      temperature: -8,
      highlights: -10,
      shadows: 12,
      noise: 15,
    },
  },
  {
    name: "Vintage Portrait",
    description: "Classic portrait film look",
    category: "Vintage & Film",
    filters: {
      brightness: 106,
      contrast: 108,
      saturation: 92,
      temperature: 6,
      highlights: -8,
      shadows: 10,
      noise: 12,
    },
  },
  {
    name: "Retro Fade",
    description: "Faded retro color palette",
    category: "Vintage & Film",
    filters: {
      brightness: 107,
      contrast: 98,
      saturation: 85,
      temperature: 4,
      highlights: -6,
      shadows: 8,
      noise: 10,
    },
  },
  {
    name: "Vintage Vibrant",
    description: "Punchy vintage colors",
    category: "Vintage & Film",
    filters: {
      brightness: 105,
      contrast: 120,
      saturation: 110,
      temperature: 8,
      highlights: -15,
      shadows: 18,
      noise: 15,
    },
  },
  {
    name: "Classic Slide",
    description: "Vintage slide film look",
    category: "Vintage & Film",
    filters: {
      brightness: 103,
      contrast: 125,
      saturation: 105,
      temperature: 5,
      highlights: -18,
      shadows: 20,
      noise: 12,
    },
  },
  {
    name: "Retro Matte",
    description: "Matte finish vintage look",
    category: "Vintage & Film",
    filters: {
      brightness: 106,
      contrast: 105,
      saturation: 88,
      temperature: 3,
      highlights: -5,
      shadows: 15,
      noise: 20,
    },
  },
  {
    name: "Vintage Soft",
    description: "Soft vintage color palette",
    category: "Vintage & Film",
    filters: {
      brightness: 105,
      contrast: 102,
      saturation: 90,
      temperature: 5,
      highlights: -8,
      shadows: 12,
      noise: 15,
    },
  },

  // Modern & Clean (15 presets)
  {
    name: "Clean Editorial",
    description: "Sharp and professional look",
    category: "Modern & Clean",
    filters: {
      brightness: 105,
      contrast: 115,
      saturation: 95,
      temperature: -5,
      highlights: -10,
      shadows: 10,
      sharpen: 25,
    },
  },
  {
    name: "Minimal White",
    description: "Bright and airy aesthetic",
    category: "Modern & Clean",
    filters: {
      brightness: 110,
      contrast: 95,
      saturation: 90,
      temperature: -2,
      highlights: 5,
      shadows: 15,
      exposure: 105,
    },
  },
  {
    name: "Modern Color",
    description: "Contemporary color grading",
    category: "Modern & Clean",
    filters: {
      brightness: 104,
      contrast: 112,
      saturation: 102,
      temperature: -3,
      highlights: -8,
      shadows: 12,
      sharpen: 20,
    },
  },
  {
    name: "Clean Portrait",
    description: "Modern portrait style",
    category: "Modern & Clean",
    filters: {
      brightness: 105,
      contrast: 108,
      saturation: 98,
      temperature: -2,
      highlights: -5,
      shadows: 8,
      sharpen: 15,
    },
  },
  {
    name: "Studio Pro",
    description: "Professional studio look",
    category: "Modern & Clean",
    filters: {
      brightness: 106,
      contrast: 115,
      saturation: 100,
      temperature: -4,
      highlights: -12,
      shadows: 15,
      sharpen: 30,
    },
  },
  {
    name: "Modern Matte",
    description: "Contemporary matte finish",
    category: "Modern & Clean",
    filters: {
      brightness: 108,
      contrast: 105,
      saturation: 95,
      temperature: -3,
      highlights: -8,
      shadows: 12,
      exposure: 102,
    },
  },
  {
    name: "Clean Contrast",
    description: "Crisp contrast enhancement",
    category: "Modern & Clean",
    filters: {
      brightness: 103,
      contrast: 120,
      saturation: 98,
      temperature: -2,
      highlights: -15,
      shadows: 18,
      sharpen: 25,
    },
  },
  {
    name: "Modern Fresh",
    description: "Fresh and clean look",
    category: "Modern & Clean",
    filters: {
      brightness: 105,
      contrast: 110,
      saturation: 105,
      temperature: -5,
      highlights: -10,
      shadows: 10,
      sharpen: 20,
    },
  },
  {
    name: "Studio Light",
    description: "Bright studio lighting",
    category: "Modern & Clean",
    filters: {
      brightness: 108,
      contrast: 105,
      saturation: 95,
      highlights: -5,
      shadows: 15,
      exposure: 104,
      sharpen: 15,
    },
  },
  {
    name: "Clean Warm",
    description: "Modern warm tones",
    category: "Modern & Clean",
    filters: {
      brightness: 105,
      contrast: 108,
      saturation: 98,
      temperature: 5,
      highlights: -8,
      shadows: 12,
      sharpen: 18,
    },
  },
  {
    name: "Modern Cool",
    description: "Contemporary cool tones",
    category: "Modern & Clean",
    filters: {
      brightness: 104,
      contrast: 110,
      saturation: 95,
      temperature: -8,
      highlights: -10,
      shadows: 15,
      sharpen: 20,
    },
  },
  {
    name: "Clean Pastel",
    description: "Soft pastel color palette",
    category: "Modern & Clean",
    filters: {
      brightness: 106,
      contrast: 102,
      saturation: 92,
      temperature: -2,
      highlights: -5,
      shadows: 10,
      exposure: 103,
    },
  },
  {
    name: "Modern Bright",
    description: "Bright and vibrant look",
    category: "Modern & Clean",
    filters: {
      brightness: 108,
      contrast: 112,
      saturation: 105,
      temperature: -3,
      highlights: -12,
      shadows: 15,
      sharpen: 22,
    },
  },
  {
    name: "Studio Black",
    description: "Rich blacks and clean contrast",
    category: "Modern & Clean",
    filters: {
      brightness: 102,
      contrast: 125,
      saturation: 98,
      temperature: -4,
      highlights: -15,
      shadows: 20,
      sharpen: 25,
    },
  },
  {
    name: "Clean Natural",
    description: "Natural enhancement",
    category: "Modern & Clean",
    filters: {
      brightness: 104,
      contrast: 108,
      saturation: 100,
      temperature: 0,
      highlights: -8,
      shadows: 10,
      sharpen: 15,
    },
  },

  // Nature & Outdoor (15 presets)
  {
    name: "Golden Hour",
    description: "Warm sunset lighting",
    category: "Nature & Outdoor",
    filters: {
      brightness: 105,
      contrast: 110,
      saturation: 115,
      temperature: 20,
      tint: -8,
      highlights: -15,
      shadows: 20,
      lightLeak: 15,
    },
  },
  {
    name: "Forest Tale",
    description: "Rich greens and earthy tones",
    category: "Nature & Outdoor",
    filters: {
      brightness: 100,
      contrast: 115,
      saturation: 120,
      temperature: -5,
      tint: 8,
      vibrance: 115,
      highlights: -10,
      shadows: 15,
    },
  },
  {
    name: "Mountain Air",
    description: "Crisp and clear outdoor look",
    category: "Nature & Outdoor",
    filters: {
      brightness: 105,
      contrast: 112,
      saturation: 105,
      temperature: -8,
      highlights: -12,
      shadows: 18,
      sharpen: 15,
    },
  },
  {
    name: "Ocean Breeze",
    description: "Cool tones with aqua emphasis",
    category: "Nature & Outdoor",
    filters: {
      brightness: 103,
      contrast: 108,
      saturation: 110,
      temperature: -10,
      tint: -5,
      highlights: -8,
      shadows: 12,
      vibrance: 110,
    },
  },
  {
    name: "Desert Heat",
    description: "Warm, sun-bleached aesthetic",
    category: "Nature & Outdoor",
    filters: {
      brightness: 108,
      contrast: 115,
      saturation: 95,
      temperature: 15,
      highlights: -20,
      shadows: 25,
      exposure: 105,
    },
  },
  {
    name: "Autumn Mood",
    description: "Warm fall colors",
    category: "Nature & Outdoor",
    filters: {
      brightness: 103,
      contrast: 112,
      saturation: 115,
      temperature: 12,
      tint: 5,
      highlights: -12,
      shadows: 15,
      vibrance: 110,
    },
  },
  {
    name: "Spring Fresh",
    description: "Bright spring colors",
    category: "Nature & Outdoor",
    filters: {
      brightness: 105,
      contrast: 108,
      saturation: 112,
      temperature: -3,
      tint: 8,
      highlights: -8,
      shadows: 12,
      vibrance: 115,
    },
  },
  {
    name: "Winter Crisp",
    description: "Cool winter tones",
    category: "Nature & Outdoor",
    filters: {
      brightness: 106,
      contrast: 115,
      saturation: 95,
      temperature: -12,
      highlights: -10,
      shadows: 15,
      sharpen: 20,
    },
  },
  {
    name: "Tropical",
    description: "Vibrant tropical colors",
    category: "Nature & Outdoor",
    filters: {
      brightness: 104,
      contrast: 110,
      saturation: 120,
      temperature: 5,
      tint: -3,
      highlights: -12,
      shadows: 15,
      vibrance: 120,
    },
  },
  {
    name: "Sunset Glow",
    description: "Warm evening light",
    category: "Nature & Outdoor",
    filters: {
      brightness: 105,
      contrast: 112,
      saturation: 110,
      temperature: 18,
      tint: -5,
      highlights: -15,
      shadows: 18,
      lightLeak: 12,
    },
  },
  {
    name: "Natural HDR",
    description: "Enhanced dynamic range",
    category: "Nature & Outdoor",
    filters: {
      brightness: 105,
      contrast: 115,
      saturation: 105,
      temperature: -2,
      highlights: -20,
      shadows: 25,
      sharpen: 15,
    },
  },
  {
    name: "Landscape Pro",
    description: "Professional landscape look",
    category: "Nature & Outdoor",
    filters: {
      brightness: 103,
      contrast: 118,
      saturation: 108,
      temperature: -5,
      highlights: -15,
      shadows: 20,
      sharpen: 18,
    },
  },
  {
    name: "Nature Soft",
    description: "Soft natural colors",
    category: "Nature & Outdoor",
    filters: {
      brightness: 104,
      contrast: 105,
      saturation: 102,
      temperature: 3,
      highlights: -8,
      shadows: 12,
      vibrance: 105,
    },
  },
  {
    name: "Wild Earth",
    description: "Rich earth tones",
    category: "Nature & Outdoor",
    filters: {
      brightness: 102,
      contrast: 115,
      saturation: 112,
      temperature: 8,
      tint: 5,
      highlights: -12,
      shadows: 18,
      vibrance: 110,
    },
  },
  {
    name: "Adventure",
    description: "Dynamic outdoor look",
    category: "Nature & Outdoor",
    filters: {
      brightness: 105,
      contrast: 120,
      saturation: 108,
      temperature: -3,
      highlights: -15,
      shadows: 20,
      sharpen: 20,
    },
  },

  // Portrait & Beauty (15 presets)
  {
    name: "Soft Portrait",
    description: "Flattering skin tones with soft focus",
    category: "Portrait & Beauty",
    filters: {
      brightness: 105,
      contrast: 95,
      saturation: 95,
      temperature: 5,
      tint: 3,
      highlights: -8,
      shadows: 12,
      blur: 0.3,
      glow: 10,
    },
  },
  {
    name: "Fashion Editorial",
    description: "High-end fashion magazine look",
    category: "Portrait & Beauty",
    filters: {
      brightness: 105,
      contrast: 120,
      saturation: 98,
      temperature: -3,
      highlights: -15,
      shadows: 20,
      sharpen: 25,
    },
  },
  {
    name: "Beauty Glow",
    description: "Soft beauty light with subtle glow",
    category: "Portrait & Beauty",
    filters: {
      brightness: 108,
      contrast: 98,
      saturation: 95,
      temperature: 3,
      highlights: -5,
      shadows: 10,
      glow: 20,
      blur: 0.2,
    },
  },
  {
    name: "Clean Beauty",
    description: "Clean, natural beauty look",
    category: "Portrait & Beauty",
    filters: {
      brightness: 106,
      contrast: 105,
      saturation: 98,
      temperature: 2,
      highlights: -8,
      shadows: 12,
      sharpen: 15,
    },
  },
  {
    name: "Portrait Pro",
    description: "Professional portrait enhancement",
    category: "Portrait & Beauty",
    filters: {
      brightness: 105,
      contrast: 112,
      saturation: 100,
      temperature: 4,
      highlights: -12,
      shadows: 15,
      sharpen: 20,
    },
  },
  {
    name: "Soft Glow",
    description: "Ethereal soft light effect",
    category: "Portrait & Beauty",
    filters: {
      brightness: 107,
      contrast: 95,
      saturation: 95,
      temperature: 3,
      highlights: -5,
      shadows: 8,
      glow: 15,
      blur: 0.2,
    },
  },
  {
    name: "Fashion Color",
    description: "Vibrant fashion colors",
    category: "Portrait & Beauty",
    filters: {
      brightness: 105,
      contrast: 115,
      saturation: 105,
      temperature: -2,
      highlights: -10,
      shadows: 15,
      sharpen: 22,
    },
  },
  {
    name: "Natural Beauty",
    description: "Enhanced natural look",
    category: "Portrait & Beauty",
    filters: {
      brightness: 104,
      contrast: 108,
      saturation: 98,
      temperature: 2,
      highlights: -8,
      shadows: 10,
      sharpen: 12,
    },
  },
  {
    name: "Studio Beauty",
    description: "Professional studio beauty",
    category: "Portrait & Beauty",
    filters: {
      brightness: 106,
      contrast: 110,
      saturation: 100,
      temperature: 0,
      highlights: -10,
      shadows: 15,
      sharpen: 18,
    },
  },
  {
    name: "Soft Matte",
    description: "Matte finish portrait look",
    category: "Portrait & Beauty",
    filters: {
      brightness: 105,
      contrast: 105,
      saturation: 95,
      temperature: 3,
      highlights: -5,
      shadows: 12,
      exposure: 102,
    },
  },
  {
    name: "Model Look",
    description: "Professional model photography",
    category: "Portrait & Beauty",
    filters: {
      brightness: 106,
      contrast: 115,
      saturation: 102,
      temperature: -2,
      highlights: -12,
      shadows: 18,
      sharpen: 25,
    },
  },
  {
    name: "Beauty Fresh",
    description: "Fresh and clean beauty",
    category: "Portrait & Beauty",
    filters: {
      brightness: 105,
      contrast: 108,
      saturation: 100,
      temperature: -1,
      highlights: -8,
      shadows: 12,
      sharpen: 15,
    },
  },
  {
    name: "Glamour",
    description: "Glamorous portrait style",
    category: "Portrait & Beauty",
    filters: {
      brightness: 107,
      contrast: 112,
      saturation: 105,
      temperature: 2,
      highlights: -10,
      shadows: 15,
      glow: 12,
    },
  },
  {
    name: "Classic Beauty",
    description: "Timeless beauty look",
    category: "Portrait & Beauty",
    filters: {
      brightness: 104,
      contrast: 110,
      saturation: 98,
      temperature: 3,
      highlights: -8,
      shadows: 12,
      sharpen: 15,
    },
  },
  {
    name: "Editorial Pro",
    description: "High-end editorial style",
    category: "Portrait & Beauty",
    filters: {
      brightness: 105,
      contrast: 118,
      saturation: 100,
      temperature: -3,
      highlights: -15,
      shadows: 20,
      sharpen: 28,
    },
  },

  // Film & Noise (10 presets)
  {
    name: "High Noise Film",
    description: "Heavy film noise with classic 35mm character",
    category: "Film & Noise",
    filters: {
      brightness: 102,
      contrast: 115,
      saturation: 95,
      temperature: 5,
      highlights: -15,
      shadows: 20,
      noise: 45,
      vignette: 15,
    },
  },
  {
    name: "Pushed Film",
    description: "High ISO pushed film look with pronounced noise",
    category: "Film & Noise",
    filters: {
      brightness: 105,
      contrast: 125,
      saturation: 90,
      temperature: 8,
      highlights: -20,
      shadows: 25,
      noise: 55,
      vignette: 20,
    },
  },
  {
    name: "Street Film",
    description: "Gritty street photography with film noise",
    category: "Film & Noise",
    filters: {
      brightness: 98,
      contrast: 120,
      saturation: 85,
      temperature: -5,
      highlights: -18,
      shadows: 22,
      noise: 40,
      vignette: 25,
    },
  },
  {
    name: "Night Film",
    description: "High sensitivity night shot simulation",
    category: "Film & Noise",
    filters: {
      brightness: 95,
      contrast: 130,
      saturation: 80,
      temperature: -10,
      highlights: -25,
      shadows: 30,
      noise: 60,
      vignette: 35,
    },
  },
  {
    name: "Grainy BW",
    description: "High contrast B&W with pronounced film noise",
    category: "Film & Noise",
    filters: {
      brightness: 100,
      contrast: 140,
      saturation: 0,
      grayscale: 100,
      highlights: -22,
      shadows: 28,
      noise: 50,
      vignette: 30,
    },
  },
  {
    name: "Expired Film",
    description: "Vintage expired film simulation with noise",
    category: "Film & Noise",
    filters: {
      brightness: 103,
      contrast: 110,
      saturation: 85,
      temperature: 12,
      tint: 8,
      highlights: -15,
      shadows: 18,
      noise: 48,
      vignette: 22,
    },
  },
  {
    name: "Ultra Noise",
    description: "Maximum film noise effect",
    category: "Film & Noise",
    filters: {
      brightness: 97,
      contrast: 135,
      saturation: 88,
      temperature: 0,
      highlights: -20,
      shadows: 25,
      noise: 75,
      vignette: 28,
    },
  },
  {
    name: "Cinematic Noise",
    description: "Movie film stock simulation",
    category: "Film & Noise",
    filters: {
      brightness: 100,
      contrast: 125,
      saturation: 92,
      temperature: -8,
      highlights: -18,
      shadows: 20,
      noise: 35,
      vignette: 25,
    },
  },
  {
    name: "Documentary",
    description: "Raw documentary style with film noise",
    category: "Film & Noise",
    filters: {
      brightness: 102,
      contrast: 118,
      saturation: 95,
      temperature: -5,
      highlights: -15,
      shadows: 18,
      noise: 42,
      vignette: 20,
    },
  },
  {
    name: "Analog Memory",
    description: "Nostalgic analog film simulation",
    category: "Film & Noise",
    filters: {
      brightness: 104,
      contrast: 112,
      saturation: 90,
      temperature: 10,
      tint: 5,
      highlights: -12,
      shadows: 15,
      noise: 38,
      vignette: 18,
    },
  },
  {
    name: "Noisy BW",
    description: "High contrast B&W with pronounced film noise",
    category: "Film & Noise",
    filters: {
      brightness: 100,
      contrast: 140,
      saturation: 0,
      grayscale: 100,
      highlights: -22,
      shadows: 28,
      noise: 50,
      vignette: 30,
    },
  },

  // Duotone & Effects (15 presets)
  {
    name: "Neon Duotone",
    description: "Vibrant neon duotone with modern effects",
    category: "Duotone & Effects",
    filters: {
      brightness: 105,
      contrast: 120,
      saturation: 110,
      duotone: true,
      duotoneColors: [
        { r: 255, g: 0, b: 128 }, // Neon Pink
        { r: 0, g: 255, b: 255 }, // Cyan
      ],
      noise: 15,
      chromaticAberration: 8,
      glow: 15,
      vignette: 25,
    },
  },
  {
    name: "Retro Purple",
    description: "Purple duotone with vintage effects",
    category: "Duotone & Effects",
    filters: {
      brightness: 102,
      contrast: 115,
      saturation: 95,
      duotone: true,
      duotoneColors: [
        { r: 147, g: 51, b: 234 }, // Purple
        { r: 255, g: 255, b: 220 }, // Cream
      ],
      noise: 30,
      lightLeak: 20,
      vignette: 30,
    },
  },
  {
    name: "Cyberpunk",
    description: "Futuristic duotone with glitch effects",
    category: "Duotone & Effects",
    filters: {
      brightness: 108,
      contrast: 130,
      saturation: 120,
      duotone: true,
      duotoneColors: [
        { r: 255, g: 66, b: 255 }, // Hot Pink
        { r: 33, g: 200, b: 255 }, // Electric Blue
      ],
      noise: 25,
      chromaticAberration: 12,
      glitch: 15,
      rgbShift: 8,
    },
  },
  {
    name: "Sunset Duo",
    description: "Warm sunset duotone blend",
    category: "Duotone & Effects",
    filters: {
      brightness: 105,
      contrast: 112,
      saturation: 108,
      duotone: true,
      duotoneColors: [
        { r: 255, g: 128, b: 0 }, // Orange
        { r: 255, g: 0, b: 128 }, // Pink
      ],
      noise: 18,
      lightLeak: 25,
      glow: 12,
      vignette: 20,
    },
  },
  {
    name: "Ocean Depths",
    description: "Deep sea duotone atmosphere",
    category: "Duotone & Effects",
    filters: {
      brightness: 98,
      contrast: 118,
      saturation: 95,
      duotone: true,
      duotoneColors: [
        { r: 0, g: 48, b: 73 }, // Deep Blue
        { r: 0, g: 173, b: 181 }, // Teal
      ],
      noise: 22,
      vignette: 35,
      glow: 8,
      chromaticAberration: 5,
    },
  },
  {
    name: "Forest Dream",
    description: "Natural green duotone blend",
    category: "Duotone & Effects",
    filters: {
      brightness: 103,
      contrast: 110,
      saturation: 100,
      duotone: true,
      duotoneColors: [
        { r: 34, g: 139, b: 34 }, // Forest Green
        { r: 255, g: 248, b: 220 }, // Cream
      ],
      noise: 15,
      lightLeak: 15,
      glow: 10,
      vignette: 22,
    },
  },
  {
    name: "Midnight Mood",
    description: "Dark mysterious duotone",
    category: "Duotone & Effects",
    filters: {
      brightness: 95,
      contrast: 125,
      saturation: 90,
      duotone: true,
      duotoneColors: [
        { r: 25, g: 25, b: 112 }, // Midnight Blue
        { r: 138, g: 43, b: 226 }, // Purple
      ],
      noise: 35,
      vignette: 40,
      chromaticAberration: 8,
      glow: 5,
    },
  },
  {
    name: "Desert Gold",
    description: "Warm desert duotone palette",
    category: "Duotone & Effects",
    filters: {
      brightness: 106,
      contrast: 115,
      saturation: 98,
      duotone: true,
      duotoneColors: [
        { r: 218, g: 165, b: 32 }, // Golden
        { r: 139, g: 69, b: 19 }, // Saddle Brown
      ],
      noise: 28,
      lightLeak: 22,
      vignette: 25,
      glow: 8,
    },
  },
  {
    name: "Electric Dreams",
    description: "Bold electric duotone mix",
    category: "Duotone & Effects",
    filters: {
      brightness: 105,
      contrast: 128,
      saturation: 110,
      duotone: true,
      duotoneColors: [
        { r: 255, g: 0, b: 255 }, // Magenta
        { r: 0, g: 255, b: 255 }, // Cyan
      ],
      noise: 20,
      chromaticAberration: 15,
      glitch: 10,
      rgbShift: 12,
    },
  },
  {
    name: "Vintage Duo",
    description: "Classic vintage duotone look",
    category: "Duotone & Effects",
    filters: {
      brightness: 102,
      contrast: 115,
      saturation: 90,
      duotone: true,
      duotoneColors: [
        { r: 101, g: 67, b: 33 }, // Brown
        { r: 255, g: 235, b: 205 }, // Blanched Almond
      ],
      noise: 42,
      lightLeak: 18,
      vignette: 30,
      oldFilm: 25,
    },
  },
  {
    name: "Arctic Frost",
    description: "Cool arctic duotone blend",
    category: "Duotone & Effects",
    filters: {
      brightness: 108,
      contrast: 110,
      saturation: 95,
      duotone: true,
      duotoneColors: [
        { r: 176, g: 224, b: 230 }, // Powder Blue
        { r: 255, g: 255, b: 255 }, // White
      ],
      noise: 15,
      glow: 18,
      chromaticAberration: 5,
      vignette: 20,
    },
  },
  {
    name: "Urban Nights",
    description: "City lights duotone effect",
    category: "Duotone & Effects",
    filters: {
      brightness: 98,
      contrast: 130,
      saturation: 85,
      duotone: true,
      duotoneColors: [
        { r: 0, g: 0, b: 139 }, // Dark Blue
        { r: 255, g: 140, b: 0 }, // Dark Orange
      ],
      noise: 45,
      chromaticAberration: 10,
      vignette: 35,
      rgbShift: 8,
    },
  },
  {
    name: "Pastel Dream",
    description: "Soft pastel duotone mix",
    category: "Duotone & Effects",
    filters: {
      brightness: 105,
      contrast: 105,
      saturation: 95,
      duotone: true,
      duotoneColors: [
        { r: 255, g: 182, b: 193 }, // Light Pink
        { r: 173, g: 216, b: 230 }, // Light Blue
      ],
      noise: 12,
      glow: 15,
      lightLeak: 12,
      vignette: 15,
    },
  },
  {
    name: "Dramatic Contrast",
    description: "High contrast duotone style",
    category: "Duotone & Effects",
    filters: {
      brightness: 100,
      contrast: 140,
      saturation: 90,
      duotone: true,
      duotoneColors: [
        { r: 0, g: 0, b: 0 }, // Black
        { r: 255, g: 255, b: 255 }, // White
      ],
      noise: 38,
      vignette: 45,
      chromaticAberration: 8,
      glow: 5,
    },
  },
  {
    name: "Candy Pop",
    description: "Sweet candy-colored duotone",
    category: "Duotone & Effects",
    filters: {
      brightness: 106,
      contrast: 115,
      saturation: 110,
      duotone: true,
      duotoneColors: [
        { r: 255, g: 105, b: 180 }, // Hot Pink
        { r: 135, g: 206, b: 235 }, // Sky Blue
      ],
      noise: 15,
      glow: 20,
      lightLeak: 15,
      chromaticAberration: 6,
    },
  },

  // Creative (30 presets)
  {
    name: "Neon Dreams",
    description: "Vibrant cyberpunk-inspired look with glowing highlights",
    category: "Creative",
    filters: {
      brightness: 110,
      contrast: 130,
      saturation: 140,
      temperature: -15,
      tint: 25,
      highlights: 30,
      shadows: -20,
      vibrance: 130,
      noise: 15,
      vignette: 40,
    },
  },
  {
    name: "Glitch Art",
    description: "Digital distortion effect with high contrast",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 150,
      saturation: 120,
      sharpen: 70,
      noise: 40,
      pixelate: 15,
      posterize: 8,
    },
  },
  {
    name: "Hologram",
    description: "Futuristic holographic effect with blue tones",
    category: "Creative",
    filters: {
      brightness: 115,
      contrast: 110,
      saturation: 130,
      temperature: -30,
      tint: 15,
      blur: 10,
      highlights: 20,
      shadows: -15,
      vibrance: 120,
    },
  },
  {
    name: "Acid Wash",
    description: "Psychedelic color effect with high saturation",
    category: "Creative",
    filters: {
      brightness: 108,
      contrast: 125,
      saturation: 160,
      temperature: 20,
      tint: -15,
      vibrance: 150,
      posterize: 5,
    },
  },
  {
    name: "8-Bit Gaming",
    description: "Retro gaming inspired pixelated look",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 120,
      saturation: 110,
      pixelate: 30,
      posterize: 12,
      noise: 10,
    },
  },
  {
    name: "Double Exposure",
    description: "Dreamy overlaid effect with soft focus",
    category: "Creative",
    filters: {
      brightness: 120,
      contrast: 90,
      saturation: 85,
      blur: 15,
      highlights: 25,
      shadows: 15,
      vignette: 30,
    },
  },
  {
    name: "Infrared",
    description: "Surreal infrared photography simulation",
    category: "Creative",
    filters: {
      brightness: 115,
      contrast: 140,
      saturation: 50,
      temperature: -40,
      tint: 30,
      highlights: 40,
      shadows: -30,
    },
  },
  {
    name: "Comic Book",
    description: "Bold comic book style with high contrast",
    category: "Creative",
    filters: {
      brightness: 110,
      contrast: 160,
      saturation: 130,
      sharpen: 60,
      posterize: 6,
      noise: 5,
    },
  },
  {
    name: "Synthwave",
    description: "80s retro-futuristic aesthetic",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 135,
      saturation: 125,
      temperature: -10,
      tint: 20,
      highlights: 25,
      shadows: -15,
      vignette: 45,
    },
  },
  {
    name: "Ethereal",
    description: "Dreamy, otherworldly atmosphere",
    category: "Creative",
    filters: {
      brightness: 112,
      contrast: 95,
      saturation: 90,
      blur: 20,
      highlights: 30,
      shadows: 20,
      vignette: 35,
    },
  },
  {
    name: "Matrix",
    description: "Digital green tint with high contrast",
    category: "Creative",
    filters: {
      brightness: 95,
      contrast: 140,
      saturation: 110,
      temperature: -15,
      tint: 40,
      highlights: -20,
      shadows: 15,
      noise: 20,
    },
  },
  {
    name: "Polaroid Fade",
    description: "Vintage instant photo effect",
    category: "Creative",
    filters: {
      brightness: 108,
      contrast: 95,
      saturation: 85,
      temperature: 10,
      blur: 5,
      vignette: 25,
      noise: 15,
    },
  },
  {
    name: "Oil Painting",
    description: "Artistic oil painting simulation",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 115,
      saturation: 120,
      sharpen: 80,
      posterize: 15,
      blur: 5,
    },
  },
  {
    name: "Dystopian",
    description: "Dark and gritty post-apocalyptic look",
    category: "Creative",
    filters: {
      brightness: 90,
      contrast: 145,
      saturation: 70,
      temperature: -20,
      highlights: -30,
      shadows: 25,
      noise: 30,
      vignette: 50,
    },
  },
  {
    name: "Pastel Dream",
    description: "Soft pastel colors with dreamy atmosphere",
    category: "Creative",
    filters: {
      brightness: 110,
      contrast: 90,
      saturation: 95,
      temperature: 5,
      tint: 10,
      highlights: 15,
      shadows: 10,
      blur: 8,
    },
  },
  {
    name: "Crystal",
    description: "Sharp, clear look with enhanced details",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 120,
      saturation: 110,
      sharpen: 90,
      highlights: -10,
      shadows: 15,
      vibrance: 115,
    },
  },
  {
    name: "Retro Wave",
    description: "Bold retro colors with strong contrast",
    category: "Creative",
    filters: {
      brightness: 108,
      contrast: 130,
      saturation: 135,
      temperature: 15,
      tint: -10,
      highlights: 20,
      shadows: -15,
      vignette: 35,
    },
  },
  {
    name: "Watercolor",
    description: "Soft watercolor painting effect",
    category: "Creative",
    filters: {
      brightness: 108,
      contrast: 95,
      saturation: 85,
      blur: 12,
      highlights: 10,
      shadows: 15,
      posterize: 10,
    },
  },
  {
    name: "Cosmic",
    description: "Space-inspired ethereal look",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 125,
      saturation: 115,
      temperature: -25,
      tint: 15,
      highlights: 30,
      shadows: -20,
      vignette: 40,
      noise: 10,
    },
  },
  {
    name: "Glitch Wave",
    description: "Distorted wave effect with artifacts",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 140,
      saturation: 120,
      pixelate: 10,
      sharpen: 50,
      noise: 25,
      posterize: 7,
    },
  },
  {
    name: "Candy Pop",
    description: "Bright and colorful candy-like colors",
    category: "Creative",
    filters: {
      brightness: 115,
      contrast: 120,
      saturation: 150,
      temperature: 10,
      tint: 5,
      vibrance: 140,
      highlights: 15,
    },
  },
  {
    name: "Pencil Sketch",
    description: "Artistic pencil drawing effect",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 150,
      saturation: 0,
      sharpen: 70,
      posterize: 15,
      noise: 5,
    },
  },
  {
    name: "Frozen",
    description: "Cool, icy blue tones",
    category: "Creative",
    filters: {
      brightness: 110,
      contrast: 105,
      saturation: 85,
      temperature: -35,
      highlights: 20,
      shadows: 10,
      blur: 5,
    },
  },
  {
    name: "Vintage Tech",
    description: "Old computer screen effect",
    category: "Creative",
    filters: {
      brightness: 98,
      contrast: 115,
      saturation: 90,
      pixelate: 8,
      noise: 15,
      posterize: 10,
      vignette: 30,
    },
  },
  {
    name: "Stardust",
    description: "Magical sparkly effect",
    category: "Creative",
    filters: {
      brightness: 112,
      contrast: 110,
      saturation: 120,
      highlights: 35,
      shadows: -10,
      blur: 5,
      noise: 8,
    },
  },
  {
    name: "Noire Glow",
    description: "Dark with glowing highlights",
    category: "Creative",
    filters: {
      brightness: 95,
      contrast: 135,
      saturation: 80,
      highlights: 40,
      shadows: -25,
      vignette: 45,
      noise: 12,
    },
  },
  {
    name: "Rainbow Haze",
    description: "Colorful dreamy effect",
    category: "Creative",
    filters: {
      brightness: 108,
      contrast: 105,
      saturation: 140,
      temperature: 15,
      tint: -10,
      blur: 10,
      vibrance: 130,
    },
  },
  {
    name: "Minimal Tech",
    description: "Clean, modern tech aesthetic",
    category: "Creative",
    filters: {
      brightness: 105,
      contrast: 115,
      saturation: 95,
      sharpen: 40,
      highlights: -10,
      shadows: 10,
      posterize: 20,
    },
  },
  {
    name: "Mystic",
    description: "Mysterious and magical atmosphere",
    category: "Creative",
    filters: {
      brightness: 102,
      contrast: 120,
      saturation: 110,
      temperature: -15,
      tint: 20,
      highlights: 25,
      shadows: -15,
      vignette: 40,
      blur: 8,
    },
  },
  {
    name: "Future Noir",
    description: "Futuristic dark aesthetic",
    category: "Creative",
    filters: {
      brightness: 95,
      contrast: 140,
      saturation: 85,
      temperature: -20,
      highlights: 30,
      shadows: -20,
      vignette: 45,
      noise: 15,
    },
  },
];
